# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  #server1
    config.vm.define "App1" do |app|
      app.vm.hostname = "app1.test"
      app.vm.network :private_network, ip: "192.168.60.4"
    end
end