apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    events {
    worker_connections 1024;
    }
    http {
       upstream dobby-svc {
        server 10.105.185.224:4444;
        }
        server {
              listen 80;
              location / {
              proxy_pass http://dobby-svc;
              }
        }
      }