# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.ssh.insert_key = false

  config.vm.synced_folder "." "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true
  end

  #server1
  config.vm.define "App1" do |app|
    app.vm.hostname = "app1.test"
    app.vm.network :private_network, ip: "192.168.60.4"
  end

  #server2
  config.vm.define "App2" do |app|
    app.vm.hostname = "app2.test"
    app.vm.network :private_network, ip: "192.168.60.5"
  end

  #DB server
  config.vm.define "db" do |app|
    app.vm.hostname = "db.test"
    app.vm.network :private_network, ip: "192.168.60.6"
  end

end
